wrap the `AppState` in an `Arc`
mainmatter/gerust pull request #136
Opened 2024-11-13 16:53 UTC by marcoow

…to avoid races

2024-11-18 09:51 UTC, hdoordt reviewed
Looks good in general! Some notes:

- the repetition of `State<Arc<AppState>>` gets a bit tedious, introducing a type alias `type GiveMeAName = Arc<AppState>;`, possibly in `web::state` would alleviate that somewhat.
- `AppState` no longer needs to be `Clone`
- The blueprints in `blueprints/cli/blueprints` need updating as well

2024-11-18 13:05 UTC, marcoow commented
@hdoordt all fixed

2024-11-19 08:38 UTC, hdoordt requested changes

2024-11-19 08:38 UTC, hdoordt commented on blueprint/cli/blueprints/middleware/file.rs.liquid.liquid
> +use std::sync::Arc;
This can be removed

2024-11-19 08:38 UTC, hdoordt commented on blueprint/cli/blueprints/controller/crud/controller.rs.liquid.liquid
> +use std::sync::Arc;
This can be removed

2024-11-19 08:38 UTC, hdoordt commented on blueprint/cli/blueprints/controller/minimal/controller.rs.liquid.liquid
> +use std::sync::Arc;
This can be removed

2024-11-19 10:17 UTC, hdoordt approved these changes

2024-11-19 10:18 UTC, merged